name: Changeset Release PR Notification

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  notify-slack:
    if: startsWith(github.event.pull_request.head.ref, 'changeset-release/')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr-details
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚀 New changeset release PR opened for jeepney-design-system!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR #${{ steps.pr-details.outputs.pr_number }}:* ${{ steps.pr-details.outputs.pr_title }}\n\n:point_right: <${{ steps.pr-details.outputs.pr_url }}|View Pull Request>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Repository: `${{ github.repository }}` | Branch: `${{ github.event.pull_request.head.ref }}` → `${{ github.event.pull_request.base.ref }}`"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
